### ISSUE TITLE
`do` handled incorrectly

### ISSUE THREAD

**Issue by aaronmueller** [aaronmueller/zsh-P4#1]
Using `do` prints two command prompts (likely due to an incorrect use of fork()--my bad) and does not print anything, regardless of what the tokens following `do` are. 

Also, it seems to interfere with future operations; `done` works incorrectly afterward.

**Comment by cmvanmeter** [comment]
Did not test if it was fixed, but I changed the section of the code to that discussed in class. fork was called incorrectly for the parent case.

**Comment by cmvanmeter** [comment]
Added full do functionality -- may need to check waitpid(), but the code itself runs w/o error as is and can recognize parent/child (tests not shown).
