### ISSUE TITLE
README

### ISSUE THREAD

**Issue by aaronmueller** [aaronmueller/zsh-P4#32]
Need to add:
* list of files in project
* brief description of project, including the algorithms used
* list of known limitations/bugs

**Comment by cmvanmeter** [comment]
List of files fully updated.

**Comment by cmvanmeter** [comment]
Added description of each command. Algorithms not discussed.

**Comment by cmvanmeter** [comment]
Added list of known limitations/bugs. Need to make sure nothing is missing.
