### ISSUE TITLE
Built Cmd: dir

### ISSUE THREAD

**Issue by cmvanmeter** [aaronmueller/zsh-P4#9]
## Issue
Need to implement **dir _directoryName_**
## Ideas
None
## Work Done
None

**Comment by cmvanmeter** [comment]
Fixed a small format problem.
I am having trouble getting the dir to change. Am I doing it wrong?
dir "/home/mylogin" does not work
dir into a directory I made does not work

**Comment by aaronmueller** [comment]
all necessary components complete; 'pwd' could be useful, but as for the graded portion of the project, this is essentially done
